# -*- coding: utf-8 -*-
"""Week_5_Assignement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQybqqW00370Y_0yp_5SRCRz_kknutUQ
"""

import pandas as pd
import numpy as np

# Creating the messy dataset
data = {
    'Name': ['Fatima', 'Muhammad', 'Aisha', 'Ali', 'Khadija', np.nan],
    'Age': [25, 30, 35, 40, 45, np.nan],
    'Gender': ['F', 'M', 'F', 'M', np.nan, 'F'],
    'DOB': ['01/15/1995', '02/20/1990', '03/25/1985', '04/30/1980', '05/05/1975', '06/10/1970'],
    'Grade': [85, 90, 95, 80, 75, 100]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Display the messy dataset
print("Messy Dataset:")
print(df)
print()

# Step 1: Standardize column names to lowercase
df.columns = df.columns.str.lower()

# Step 2: Handle missing values
# Impute missing numerical values with the mean
df['age'].fillna(df['age'].mean(), inplace=True)
# Remove rows with missing categorical values
df.dropna(subset=['gender'], inplace=True)

# Step 3: Convert date column to datetime format
df['dob'] = pd.to_datetime(df['dob'], format='%m/%d/%Y')

# Step 4: Identify and remove outliers in the grade column
Q1 = df['grade'].quantile(0.25)
Q3 = df['grade'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['grade'] >= Q1 - 1.5 * IQR) & (df['grade'] <= Q3 + 1.5 * IQR)]

# Display the cleaned dataset
print("Cleaned Dataset:")
print(df)